# Data types in Numba

 - Elwin van 't Wout
 - Pontificia Universidad Católica de Chile
 - IMT3870
 - 28-8-2023

This tutorial shows the sensitivity of Numba to data types.

In [1]:
from numba import jit
import numpy as np

Let us create a function that adds a given matrix to the input variable. Since the matrix is of integer type, we specify this explicitly as well.

In [2]:
@jit(nopython=True)
def add_to_matrix(x):
    my_matrix = np.array([[11, 12, 13], [21, 22, 23]])
    sum = my_matrix + x
    return sum

In [3]:
@jit(nopython=True)
def add_to_matrix_int(x):
    my_matrix = np.array([[11, 12, 13], [21, 22, 23]], dtype=int)
    sum = my_matrix + x
    return sum

In [4]:
@jit(nopython=True)
def add_to_matrix_npint(x):
    my_matrix = np.array([[11, 12, 13], [21, 22, 23]], dtype=np.int)
    sum = my_matrix + x
    return sum

In [5]:
@jit(nopython=True)
def add_to_matrix_npint32(x):
    my_matrix = np.array([[11, 12, 13], [21, 22, 23]], dtype=np.int32)
    sum = my_matrix + x
    return sum

In [6]:
@jit(nopython=True)
def add_to_matrix_npint64(x):
    my_matrix = np.array([[11, 12, 13], [21, 22, 23]], dtype=np.int64)
    sum = my_matrix + x
    return sum

Let's apply the functionality to a matrix with the same size and data type.

In [7]:
matrix_int_2_x_3 = np.array([[1, 2, 3], [4, 5, 6]], dtype=int)
print("Matrix:\n", matrix_int_2_x_3)
print("Data type:", matrix_int_2_x_3.dtype)

Matrix:
 [[1 2 3]
 [4 5 6]]
Data type: int32


In [8]:
result_int_2_x_3 = add_to_matrix(matrix_int_2_x_3)
print(result_int_2_x_3)

[[12 14 16]
 [25 27 29]]


In [9]:
result_int_2_x_3 = add_to_matrix_int(matrix_int_2_x_3)
print(result_int_2_x_3)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
No implementation of function Function(<built-in function array>) found for signature:
 
 >>> array(list(list(int64)<iv=None>)<iv=None>, dtype=Function(<class 'int'>))
 
There are 2 candidate implementations:
  - Of which 2 did not match due to:
  Overload in function 'impl_np_array': File: numba\np\arrayobj.py: Line 5242.
    With argument(s): '(list(list(int64)<iv=None>)<iv=None>, dtype=Function(<class 'int'>))':
   Rejected as the implementation raised a specific error:
     TypingError: The argument "dtype" must be a data-type if it is provided
  raised from c:\Users\alber\AppData\Local\Programs\Python\Python311\Lib\site-packages\numba\np\arrayobj.py:5250

During: resolving callee type: Function(<built-in function array>)
During: typing of call at C:\Users\alber\AppData\Local\Temp\ipykernel_7200\720094321.py (3)


File "..\..\..\..\..\..\AppData\Local\Temp\ipykernel_7200\720094321.py", line 3:
<source missing, REPL/exec in use?>


In [10]:
result_int_2_x_3 = add_to_matrix_npint(matrix_int_2_x_3)
print(result_int_2_x_3)

TypingError: Failed in nopython mode pipeline (step: nopython frontend)
Internal error at resolving type of attribute "int" of "$52load_global.12".
module 'numpy' has no attribute 'int'.
`np.int` was a deprecated alias for the builtin `int`. To avoid this error in existing code, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
The aliases was originally deprecated in NumPy 1.20; for more details and guidance see the original release note at:
    https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
During: typing of get attribute at C:\Users\alber\AppData\Local\Temp\ipykernel_7200\2945082661.py (3)
Enable logging at debug level for details.

File "..\..\..\..\..\..\AppData\Local\Temp\ipykernel_7200\2945082661.py", line 3:
<source missing, REPL/exec in use?>


In [11]:
result_int_2_x_3 = add_to_matrix_npint32(matrix_int_2_x_3)
print(result_int_2_x_3)

[[12 14 16]
 [25 27 29]]


In [12]:
result_int_2_x_3 = add_to_matrix_npint64(matrix_int_2_x_3)
print(result_int_2_x_3)

[[12 14 16]
 [25 27 29]]


The result is indeed as expected, the sum of the two matrices. However, the second implementation raises an error. Reading the error message suggests a problem with the data type. This is strange, because the matrix to add was defined with ```dtype=int``` as in the Numba function. Still it raises an error since ```int``` is a data type managed by Python and ```np.int64``` a data type managed by NumPy.

Regardless of this specific example, it is recommended to check data types when using Numba. It is a common error to have incompatibilities in data type since Numba infers the data type from the function and optimises the code accordingly.